version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/auth_serv/*.proto --go_out=./generated/go/ --go_opt=paths=source_relative --go-grpc_out=./generated/go/ --go-grpc_opt=paths=source_relative
